# Generated by Django 5.0.6 on 2024-07-05 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=' ', max_length=100)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadastro.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_modelo', models.IntegerField(default=0)),
                ('ano_fabricacao', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observacao', models.CharField(max_length=255)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadastro.modelo')),
            ],
        ),
    ]
